### ISSUE TITLE
RuntimeError: applying transform <fmcib.preprocessing.seed_based_crop.SeedBasedPatchCropd

### ISSUE THREAD

**Issue by skim2257** [AIM-Harvard/foundation-cancer-image-biomarker#298]
## 🐛 Bug Report
Running get_features() on our dataset broke the script and outputted the following errors

## 🔬 Full error
```
2024-05-03 15:36:30.354 | INFO     | fmcib.run:get_features:47 - Running inference over batches ...
  0%|                                                                    | 0/731 [00:23<?, ?it/s]

Traceback (most recent call last):
  File "/cluster/home/sejinkim/projects/aim-unicorn/code/infer.py", line 6, in <module>
    feature_df = get_features(params.input_path, weights_path=params.weights_path)
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/fmcib/run.py", line 50, in get_features
    for batch in tqdm(dataloader, total=len(dataloader)):
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/fmcib/preprocessing/seed_based_crop.py", line 69, in __call__
    d[key] = self.cropper(d[key], center=center, global_coordinates=self.global_coordinates)
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/fmcib/preprocessing/seed_based_crop.py", line 133, in __call__
    assert min_d < max_d, "Invalid coordinates: min_d >= max_d"
AssertionError: Invalid coordinates: min_d >= max_d

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <fmcib.preprocessing.seed_based_crop.SeedBasedPatchCropd object at 0x7f587da48c10>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/data/dataset.py", line 112, in __getitem__
    return self._transform(index)
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/data/dataset.py", line 98, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f587da491e0>
```

### Code sample
Just one line after parsing arguments:
`feature_df = get_features(params.input_path, weights_path=params.weights_path)`

### Environment

* OS: Linux
* Python version, get it with: Python 3.10.14

**Comment by surajpaib** [comment]
Hi @skim2257 

Could you please confirm that the visualization check works as expected?

See it mentioned here below the note:
https://aim-harvard.github.io/foundation-cancer-image-biomarker/getting-started/quick-start/

**Comment by skim2257** [comment]
Thanks for the quick reply @surajpaib 

This is the error I receive when attempting to run `visualize_seed_point`
```
ModuleNotFoundError: No module named 'fmcib.visualize'
```

### version
`foundation-cancer-image-biomarker` = 1.0.0
`python` = 3.10.14

When attempting to install with the pre-release flag (if visualize is exclusively in the pre-release), I receive the following error: 
```
ERROR: Ignored the following versions that require a different python version: 0.0.1a0 Requires-Python >=3.8,<4.0; 0.0.1a1 Requires-Python >=3.8,<4.0; 0.0.1a10 Requires-Python >=3.8,<4.0; 0.0.1a11 Requires-Python >=3.8,<4.0; 0.0.1a12 Requires-Python >=3.8,<4.0; 0.0.1a13 Requires-Python >=3.8,<4.0; 0.0.1a14 Requires-Python >=3.8,<4.0; 0.0.1a15 Requires-Python >=3.8,<4.0; 0.0.1a16 Requires-Python >=3.8,<4.0; 0.0.1a17 Requires-Python >=3.8,<4.0; 0.0.1a18 Requires-Python >=3.8,<4.0; 0.0.1a19 Requires-Python >=3.8,<4.0; 0.0.1a2 Requires-Python >=3.8,<4.0; 0.0.1a20 Requires-Python >=3.8,<4.0; 0.0.1a21 Requires-Python >=3.8,<3.12; 0.0.1a22 Requires-Python >=3.8,<3.12; 0.0.1a23 Requires-Python >=3.8,<3.12; 0.0.1a24 Requires-Python >=3.8,<3.12; 0.0.1a25 Requires-Python >=3.8,<3.12; 0.0.1a26 Requires-Python >=3.8,<3.12; 0.0.1a27 Requires-Python >=3.8,<3.12; 0.0.1a28 Requires-Python >=3.8,<3.12; 0.0.1a29 Requires-Python >=3.8,<3.12; 0.0.1a3 Requires-Python >=3.8,<4.0; 0.0.1a30 Requires-Python <3.12,>=3.8; 0.0.1a31 Requires-Python <3.12,>=3.8; 0.0.1a32 Requires-Python <3.12,>=3.8; 0.0.1a33 Requires-Python <3.12,>=3.8; 0.0.1a34 Requires-Python <3.12,>=3.8; 0.0.1a35 Requires-Python <3.12,>=3.8; 0.0.1a36 Requires-Python <3.12,>=3.8; 0.0.1a4 Requires-Python >=3.8,<4.0; 0.0.1a5 Requires-Python >=3.8,<4.0; 0.0.1a6 Requires-Python >=3.8,<4.0; 0.0.1a7 Requires-Python >=3.8,<4.0; 0.0.1a8 Requires-Python >=3.8,<4.0; 0.0.1a9 Requires-Python >=3.8,<4.0; 1.0.0 Requires-Python <3.12,>=3.8; 1.0.1a0 Requires-Python <3.12,>=3.8
ERROR: Could not find a version that satisfies the requirement foundation-cancer-image-biomarker (from versions: none)
ERROR: No matching distribution found for foundation-cancer-image-biomarker
```

**Comment by surajpaib** [comment]
Thanks for checking this out @skim2257 

There's been a mistake in the docs, the correct import for the function is.

```python
from fmcib.visualization.verify_io import visualize_seed_point
```

Apologies for any inconvenience!

This should be updated in the docs momentarily with some additional tooltips on what might be issues with coordinates.

**Comment by surajpaib** [comment]
> Hi @skim2257
> 
> Could you please confirm that the visualization check works as expected?
> 
> See it mentioned here below the note: https://aim-harvard.github.io/foundation-cancer-image-biomarker/getting-started/quick-start/


The docs should be updated now!

**Comment by skim2257** [comment]
Hi Suraj, 

Thanks for clarifying the import. This is the error I got:
```
Traceback (most recent call last):
  File "/cluster/home/sejinkim/projects/aim-unicorn/code/validate.py", line 12, in <module>
    visualize_seed_point(df_new.iloc[0])
  File "/cluster/home/sejinkim/miniconda3/envs/fmcib/lib/python3.10/site-packages/fmcib/visualization/verify_io.py", line 60, in visualize_seed_point
    assert min_d < max_d, "Invalid coordinates: min_d >= max_d"
AssertionError: Invalid coordinates: min_d >= max_d
```

**Comment by surajpaib** [comment]
@skim2257 

This most likely means that the coordinates are not in the format FMCIB expects them to be. Can you detail out the process you use to obtain the coordinates?

Here is a tutorial for how you can extract them using SITK from mask files (which might be your usecase): https://github.com/AIM-Harvard/foundation-cancer-image-biomarker/blob/master/tutorials/get_seed_from_mask.ipynb

**Comment by skim2257** [comment]
Ah... I was using the voxel coordinates, but it seems the function expects the physical coordinate space. 
I'll make those changes and update this thread on how it goes. Thanks!

**Comment by skim2257** [comment]
@surajpaib I noticed in the `visualize_seed_point` function, there was an option to feed in the label_path instead. 
Could I add that column to the spreadsheet and feed that into the `get_features` function as well?

**Comment by surajpaib** [comment]
Unfortunately, that feature isn't in the `get_features` function. The reason this is not provided by default is so that the coordinates are manually verified before being sent for feature extraction.

**Comment by skim2257** [comment]
Yep, removed `mask.TransformPhysicalPointToIndex(centroid_coords)` and the features extracted perfectly well. 
Thank you!
